config/routes.rb
Rails.application.routes.draw do
  root 'showcase#index'
  post 'toggle_time_format' => 'showcase#toggle_time_format'
  post 'change_theme' => 'showcase#change_theme'
  post 'add_city' => 'showcase#add_city'
  post 'del_city' => 'showcase#del_city'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/timezone.rb
class Timezone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/showcase_controller.rb
class ShowcaseController < ApplicationController
  before_action :ensure_time_format_exists
  before_action :ensure_selected_cities_exists
  before_action :ensure_theme_exists

  def index
    @selectedCities = session[:selected_cities]
    @time_format_twenty_four = session[:time_format]==24? true : false;
    @theme = session[:theme]
  end

  #change time format from 24 hr to 12 and vice versa
  def toggle_time_format 
    temp = session[:time_format];
    if temp == 24
      session[:time_format] = 12;
    else
      session[:time_format] = 24;
    end
    redirect_to root_path;
  end

  #change design theme POST
  def change_theme
    session[:theme] = params['theme'];
    redirect_to root_path;
  end 

  #add city
  def add_city
    if !params[:anything][:city].present?
      flash[:danger] = "Error! No city entered"
      redirect_to root_path
    else
      if cityExists(params[:anything][:city])
        if already_added(params[:anything][:city])
          flash[:danger] = "Error! The city has been added before"
        else
          session[:selected_cities].push(params[:anything][:city]);
        end
      else
        flash[:danger] = "Error! No such city exists"
      end
      redirect_to root_path;
    end
  end 

  #delete city
  def del_city
    session[:selected_cities].delete(params[:button]);
    redirect_to root_path;
  end

  private
  #initialize the time format session
  def ensure_time_format_exists
    session[:time_format] ||= "24";
  end
  #initialize selected cities
  def ensure_selected_cities_exists
    session[:selected_cities] ||= ["Auckland", "Honolulu"];
  end
  #initialize theme
  def ensure_theme_exists
    session[:theme] ||= "black";
  end

  #returns true if the city exists
  def cityExists(city)
    @temp = city + "%";
    @temp.prepend("%")
    timezone = Timezone.where("array_to_string(utc, '||') ILIKE :name", name: @temp)
    if timezone && timezone.length > 0
      return true
    else
      return false
    end
  end

  #finds if the city is already added
  def already_added(city)
    if session[:selected_cities] && session[:selected_cities].length > 0
      return session[:selected_cities].include? city
    else
      return false 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/showcase_helper.rb
module ShowcaseHelper
    #takes a city as param and returns the time difference with local time
    def get_difference(city)
        timezone = get_zone(city)[0]
        value = timezone.offset - 10
        string = value>0? '+' + value.to_s + 'h' : value.to_s + 'h'
        return string
    end

    #takes a city as parameter and returns if the day is tomorrow, today or yesterday by comparing with local time
    def get_day(city)
        timezone = get_timezone(city)
        if Time.current.month == Time.current.in_time_zone(timezone).strftime("%m").to_i
            if Time.current.day == Time.current.in_time_zone(timezone).strftime("%d").to_i
                return "Today"
            elsif Time.current.in_time_zone(timezone).strftime("%d").to_i > Time.current.day
                return "Tomorrow"
            else
                return "Yesterday"
            end
        elsif Time.current.in_time_zone(timezone).strftime("%m").to_i > Time.current.month
            if Time.current.in_time_zone(timezone).strftime("%Y").to_i == Time.current.year 
                return "Tomorrow"
            else
                return "Yesterday"
            end
        else
            if Time.current.in_time_zone(timezone).strftime("%Y").to_i == Time.current.year 
                return "Yesterday"
            else
                return "Tomorrow"
            end
        end
    end

    #takes a city as param and returns a utc value
    def get_timezone(city)
        return get_zone(city)[0].utc[0]
    end

    #takes a city as param and returns a utc value
    def get_zone(city)
        @temp = city + "%";
        @temp.prepend("%")
        timezone = Timezone.where("array_to_string(utc, '||') ILIKE :name", name: @temp)
        return timezone
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="footer-row">
        <div class="student-info">
            <div>Clock+</div>
            <div>Email: s3642965@student.rmit.edu.au</div>
            <div>Attempt grade level: DI</div>
        </div>
        <div class="links">
            <div class="link">Share Social</div>
            <div class="link"><%= link_to "http://www.facebook.com/tanzim012" do %>
                <%= image_tag 'facebook.png', width: "30", height: "30"%>
            <% end %>
            </div>
            <div class="link"><%= link_to "https://twitter.com/botmon36" do %>
                <%= image_tag 'twitter.png', width: "30", height: "30"%>
            <% end %>
            </div>
            <div class="link"><%= link_to "https://www.linkedin.com/in/tshahriar/" do %>
                <%= image_tag 'linkedin.png', width: "30", height: "30" %>
            <% end %>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
    <div class="navbar-container">
      <h3>Clock+</h3>
      <div class="header-row">
        <li class="<%= 'btn btn-success active' if current_page?(root_path) %>">Showcase<%= link_to root_path %></li>
        <li class="<%= 'btn' %>"> <%= mail_to "s3642965@student.rmit.edu.au", "Contact Us", id: "contact-btn" %></li>
      </div>
    </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clock+</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>
  </head>

  <body class="<%=session[:theme] %>">
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/showcase/_add_btn.html.erb
<%= form_for :anything, url: add_city_path do |form| %>
    <div class="add-btn">
        <%= form.text_field :city, class: 'add-city-textfield', placeholder: "Add a city here..." %>
        <%= form.submit "Add", class: "btn btn-primary btn-lg" %>
    </div>
<% end %>

app/views/showcase/_twelve_format.html.erb
<div class="cities-container">
    <div class="city-container">
        <div class="city-name">
            Melbourne
        </div>
        <div class="city-time-container">
            <div class="time">
                <%=Time.current.strftime("%I:%M") %>
                <div class="am-pm">
                    <%=Time.current.strftime("%p") %>
                </div>
            </div>
            <% if (Time.current.strftime("%H").to_i >= 9) && (Time.current.strftime("%H").to_i <= 17) %>
                <div class="day">Today <span class="glyphicon glyphicon-stop text-success" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.strftime("%H").to_i >= 18) && (Time.current.strftime("%H").to_i <= 19) %>
                <div class="day">Today <span class="glyphicon glyphicon-stop text-warning" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.strftime("%H").to_i == 8) %>
                <div class="day">Today <span class="glyphicon glyphicon-stop text-danger" aria-hidden="true"></span></div>
            <% end %>
            <%if (Time.current.strftime("%H").to_i >= 20) && (Time.current.strftime("%H").to_i <= 22) %>
                <div class="day">Today <span class="glyphicon glyphicon-stop text-danger" aria-hidden="true"></span></div>
            <%end%>
            <% if (Time.current.strftime("%H").to_i >= 23) %>
                <div class="day">Today <span class="glyphicon glyphicon-plane text-default" aria-hidden="true"></span></div>
            <% end %>
            <%if (Time.current.strftime("%H").to_i <= 7) %>
                <div class="day">Today <span class="glyphicon glyphicon-plane text-default" aria-hidden="true"></span></div>
            <% end %>
        </div>
    </div>
<div class="divider"></div>

<% @selectedCities.each do |city| %>
    <div class="city-container">
        <div class="city-name">
            <div><%=city%></div>
            <div class="difference"><%= get_difference(city) %></div>
        </div>
        <div class="city-time-container">
            <div class="time">
                <%=Time.current.in_time_zone(get_timezone(city)).strftime("%I:%M") %>
                    <div class="am-pm">
                        <%=Time.current.in_time_zone(get_timezone(city)).strftime("%p") %>
                    </div>
            </div>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i >= 9) && (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i <= 17) %>
                <div class="day"><%=get_day(city)%> <span class="glyphicon glyphicon-stop text-success" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i >= 18) && (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i <= 19) %>
                <div class="day"><%=get_day(city)%> <span class="glyphicon glyphicon-stop text-warning" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i == 8) %>
                <div class="day"><%=get_day(city)%> <span class="glyphicon glyphicon-stop text-danger" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i >= 20) && (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i <= 22)%>
                <div class="day"><%=get_day(city)%> <span class="glyphicon glyphicon-stop text-danger" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i >= 23) %>
                <div class="day"><%=get_day(city)%> <span class="glyphicon glyphicon-plane text-default" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i <= 7) %>
                <div class="day"><%=get_day(city)%> <span class="glyphicon glyphicon-plane text-default" aria-hidden="true"></span></div>
            <% end %>
        </div>
        <div class="close-btn">
            <%= form_for :anything, local:true, url: del_city_path do |form| %>
                <%= button_tag(type: "submit", class: "close-icon", value: city) do %>
                    <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                <% end %> 
            <%end%>
        </div>
    </div>
    <div class="divider"></div>
<%end%>
</div>
            

app/views/showcase/_twentyfour_format.html.erb
<div class="cities-container">
    <div class="city-container">
        <div class="city-name">
            Melbourne
        </div>
        <div class="city-time-container">
            <div class="time"><%=Time.current.strftime("%H:%M") %></div>
            <% if (Time.current.hour.to_i >= 9) && (Time.current.hour.to_i <= 17) %>
                <div class="day">Today
                <span class="glyphicon glyphicon-stop text-success" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.hour.to_i >= 18) && (Time.current.hour.to_i <= 19) %>
                <div class="day">Today
                <span class="glyphicon glyphicon-stop text-warning" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.hour.to_i == 8) %>
                <div class="day">Today
                <span class="glyphicon glyphicon-stop text-danger" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.hour.to_i >= 20) && (Time.current.hour.to_i <= 22)%>
                <div class="day">Today
                <span class="glyphicon glyphicon-stop text-danger" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.hour >= 23) %>
                <div class="day">Today
                <span class="glyphicon glyphicon-plane text-default" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.hour <= 7) %>
                <div class="day">Today
                <span class="glyphicon glyphicon-plane text-default" aria-hidden="true"></span></div>
            <% end %>
        </div>
    </div>
<div class="divider"></div>

<% @selectedCities.each do |city| %>
    <div class="city-container">
        <div class="city-name">
            <div><%=city%></div>
            <div class="difference"><%= get_difference(city) %></div>
        </div>
        <div class="city-time-container">
            <div class="time"><%=Time.current.in_time_zone(get_timezone(city)).strftime("%H:%M") %></div>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i >= 9) && (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i <= 17) %>
                <div class="day"><%=get_day(city)%>
                <span class="glyphicon glyphicon-stop text-success" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i >= 18) && (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i <= 19) %>
                <div class="day"><%=get_day(city)%>
                <span class="glyphicon glyphicon-stop text-warning" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i == 8) %>
                <div class="day"><%=get_day(city)%>
                <span class="glyphicon glyphicon-stop text-danger" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i >= 20) && (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i <= 22) %>
                <div class="day"><%=get_day(city)%>
                <span class="glyphicon glyphicon-stop text-danger" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i >= 23) %>
                <div class="day"><%=get_day(city)%>
                <span class="glyphicon glyphicon-plane text-default" aria-hidden="true"></span></div>
            <% end %>
            <% if (Time.current.in_time_zone(get_timezone(city)).strftime("%H").to_i <= 7)%>
                <div class="day"><%=get_day(city)%>
                <span class="glyphicon glyphicon-plane text-default" aria-hidden="true"></span></div>
            <% end %>
        </div>
        <div class="close-btn">
            <%= form_for :anything, local:true, url: del_city_path do |form| %>
                <%= button_tag(type: "submit", class: "close-icon", value: city) do %>
                    <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                <% end %> 
            <%end%>
        </div>
    </div>
    <div class="divider"></div>
<%end%>
</div>
            

app/views/showcase/index.html.erb
<div class="main-container">
    <h2>Clock+</h2>
    <div class="subtitle">Clock+ built by Tanzim Shahriar - s3642965@student.rmit.edu.au - DI - Group 4 Alex</div>
    <div class="clock-row">
        <div class="time-type-container">
            <div><span class="glyphicon glyphicon-stop text-success" aria-hidden="true"></span>Business time</div>
            <div><span class="glyphicon glyphicon-stop text-warning" aria-hidden="true"></span>Business overtime</div>
            <div><span class="glyphicon glyphicon-stop text-danger" aria-hidden="true"></span>Personal time</div>
            <div><span class="glyphicon glyphicon-plane text-default" aria-hidden="true"></span>Sleeping time</div>
        </div>
        <div class="clock-container">
            <div class="scroll"></div>
            <div>
                <%= render 'showcase/add_btn' %>
            </div>
            <div class="divider"></div>
            <%if @time_format_twenty_four %>
                <%= render 'showcase/twentyfour_format' %>
            <%else%>
                <%= render 'showcase/twelve_format' %>
            <%end%>
        </div>
        <div class="options-container">
            <div class="color">
                <h5>Color theme</h5>
                <div class="theme-button-container">
                    <%= button_to "Black", {:controller => "showcase", :action => "change_theme" } , :params => {:theme => "black"}, :method=>:post %>
                    <%= button_to 'Graphite', {:controller => "showcase", :action => "change_theme" } , :params => {:theme => "graphite"}, :method=>:post %>
                    <%= button_to 'White', {:controller => "showcase", :action => "change_theme" } , :params => {:theme => "white"}, :method=>:post %>
                </div>
                <div>
                    <%= form_for :anything, url: toggle_time_format_path do |form| %>
                        <%= form.check_box :visible,:id => "checkbox", :onclick => "this.form.submit()", checked: @time_format_twenty_four %>24 hour clock
                    <% end  %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/showcase/toggle_time_format.html.erb
<%= session.to_hash %>